---
title: efficient-study-and-collaborations
author: Chun-Jie Liu
date: '2018-08-07'
slug: efficient-study-and-collaborations
categories: []
tags: []
---


> 这个Post主要是分享一下效率学习和多人协作的个人方案。每个人有自己学习模式和使用习惯，通常用顺手了就不太愿意再去使用新的东西。借鉴别人效率管理工具和项目推进模式最自己的使用习惯和思维方式上面都是具有帮助的。这里我分享我个人以及合作的一些想法和工具，大家有什么其他的建议也可以在后面留言，以帮助其他人进步，自己也可以学习新的东西。

## 期刊订阅
对于研究生而言，高效而大量的阅读文献是必不可少的。看最新的文献可以给与我们新的思路和启发，同时也可以学习里面的方法和画图。最最总重要的是大量阅读文献对自己的论文写作是非常有帮助的。这个部分在之前的一个Post里面写过了，主要是通过期刊邮件订阅以及关键字推送和Twitter关注。大家可以看前面的一篇[Post](http://bioinfo.life.hust.edu.cn/bbs/read.php?tid=240&fid=11)。

## 项目管理
> 这里我们不讨论项目计划以及可行性，仅对项目推进上的个人管理进行介绍。

一个新的项目从创建到结题，时间周期比较长。通常开始新项目的新鲜感以及学习新知识的冲动在3-4周，如果没有令自己满意的结果，这段时期过了就会变成进度缓慢不知所措的时期。这个时间稍长便会开始怀疑项目的意义，以及推翻不断推翻重来的过程。最后的结果就是项目流产或者水一个小文章。高效的学习和项目推进的方法就变得相对比较重要。

项目创建、推进、结束、写文章这一些步骤都是项目管理的范畴。这里除了科研项目还分享一下其他代办事项，后面以我们GSCALite项目为例子再来具体说明。

### 日程管理
在项目不多的时候可以根据自己大脑来记忆，但是当事情多的时候，就需要用日程来管理。首先能够提醒自己在什么时期干什么，把时间分配好。日程有很多新颖的软件，我使用自带的日历。windows的Outlook也有日历，在美国主要使用邮件交流是，会通过邮箱穿件日程给其他人分享会议时间地点等。准确的时间提醒可以帮助自己更集中精力干手头的事情，根据日程时间和任务优先级来按顺序完成任务。Cell的webinar有提供Calendar格式和Outlook格式的日程提醒，有感兴趣的webinar可以看一下。

p0

QQ也有日历功能，我将本地日历也同步到QQ里面。

p01

### 云盘使用
云盘有很多，大家可以选择自己习惯的云盘。我主要使用[icloud](http://icloud.com/)和[坚果云](https://www.jianguoyun.com/)。坚果云使用的是免费版本，每个月可以免费上传1G，也可以像斐斐一样使用付费服务。坚果云适合项目推进的时候使用，能够实时同步并且可以保存很多个版本，也有手机版，临时需要使用的时候，可以在手机里面查找。每个项目来了，就编号命名，能够有效的管理。

p1

icloud主要使用它来存储和备份，每个项目结束之后，都会把它们从坚果云备份到icloud里面，什么时候需要用的时候在在从里面找出来。一般情况下都是不在电脑前面，然后突然需要使用以前的文档，就可以从手机里面取出来分享。

p2


### 项目推进

项目有效的推进是特别重要的，比如需要做一个分析，需要哪些步骤，将步骤列出来，完成一个勾掉一个，Outlook里面好像也有这个功能。我使用的是[Trello](http://trello.com)，从16年一直使用到现在。通常看到需要提交的材料，里面有一系列清单。可以自己列一个清单，完成一个就勾选一个。下面图片是博士后入站需要的材料，完成一份就勾选一份。

p3

### 多人协作
多人协作对于我们实验室的小团队基本上可以使用免费版本就可以了。多人协作主要包括日历、to-do（Trello）、文档、代码的共享和共同操作。

日历是可以邀请人跟你一起共享日历。Trello可以共享to-do，来共同推进项目，并且评论完成度的。

文档共享，美国实验室使用的是Dropbox。美国老板为每个人建了一个文件夹，然后通过向文件夹里面添加文档来管理所有人的项目。国内的替代品就是坚果云，下面是我与郭老师以及斐斐等共享的文件夹。ppt和图片可以放在里面，直接可以同步到多个人的电脑里面。文章修改也可以直接在里面修改其他人也可以修改同一个文件。不用每个人按照日期和名字重新创建一份。因为坚果云会保留多个版本，所以具有回滚机制来保证文档尽可能不会出错。我的毕业论文就是跟郭老师共享，郭老师直接在里面修改的。

p4

代码共享主要是通过GitHub来实现的，也有其他GitLab等替代品。通常一个项目可能有其他人参与，多个人来写代码使用GitHub来多人协作可以避免冲突，完善的分支和回滚机制保证每次的修改都可以回滚。刘腾的EVmiRNA就是通过GitHub来实现三人远程协作来实现的。GitHub的多人协作之前在[bbs](http://bioinfo.life.hust.edu.cn/bbs/read.php?tid=225)上面已经分享过了，有需要的同学可以看一下。

p5

### GSCALite例子
p6

这个是我斐斐还有张琼师兄三个人共同完成的，其中出错了几次使用的是GitHub回滚机制找回代码的。三人协作主要的问题是冲突解决，GitHub会自动标出多人修改的同一个文件，能够有效的把各自的模块分开实现。

p7

构建好了web server之后就是写文章和投稿，文章和投稿是跟郭老师共享的，里面每个文件都是多人共享可以共同修改的，这样能够高效的解决冲突，并且有足够的备份防止出错。
